### ISSUE TITLE
Email Deliverables for 5-23 Class Meeting

### ISSUE THREAD

**Issue by lukemoorhous** [chandlerbrtek/receiptscanner#1]
Harvey Siy wants us to email a set of deliverables to him for our upcoming class meeting. He's asked for our team composition, our team ideas, and our shared project folder. The shared folder has been shared with him already. We may want to consider sharing our Github with him as well.

Information for the deliverable:

Shared Project Folder: Google Drive - Seal Team 6

Team Composition: 
1. Project Manager - Joey
2. Scribe - Luke, Chandler, Joey (Weekly rotation)
3. Architect - Luke
4. QA - Chandler
5. Tech Support - Savon
6. Software Development - All

Project Ideas:
Catalog receipts within a database.
Parse receipts from a picture.
Create an integrated mobile application to use a phone camera to scan and parse receipts.
Use a cloud approach to offload processing requirements from the client device.
Provide a populated receipt form from the receipt scan.
Allow for manual entry.
Parse for totals and vendors.
Parse itemized expenses from receipts.
Generate visual reports of receipt-based expenditures.
Integrate receipt data with larger context financial data.
Create financial app integrating receipt parsing, expenditure tracking, budgeting, and planning.

**Comment by lukemoorhous** [comment]
I listed some project ideas that we discussed on Sunday and that I've been thinking about these past few days. Guys, feel free to add, remove, or edit these. To whoever emails Harvey, use this list as a guideline if you'd like.

**Comment by lukemoorhous** [comment]
Joey, feel free to toss this case back to me or somebody else; I just assigned this to you since you're the project manager. We need to email him before class on Thursday though!

**Comment by chandlerbrtek** [comment]
I’ll email Harvey today if no one else has!

**Comment by lukemoorhous** [comment]
Hey Chandler, I think Joey is going to make a draft email tonight

**Comment by NobleOrder** [comment]
I just woke up so I'm gonna work on it in a bit here

**Comment by lukemoorhous** [comment]
Joey sent the email to Harvey Siy.
