### ISSUE TITLE
Implement algorithm that finds total/other info in receipt JSON

### ISSUE THREAD

**Issue by chandlerbrtek** [chandlerbrtek/receiptscanner#17]
There could be a few different ways of doing it. For date, there would need to be a lot of different case handling. For total, maybe it's just the biggest decimal separated number it finds. Afterwards, an API call to the database is made.

**Comment by lukemoorhous** [comment]
Should this call upon the database directly? If we're going to open this up for confirmation from the user we would need to save this to the database, then populate a confirmation form for the user, then update the record if the user wishes to correct/add data. With this approach we would need, at a worst case, 2-3 database calls.

We can reduce this to a single call by using our result interpreter to populate the fields within our data object, then displaying the object's data to the user with our form. After the user confirms the data it would then be saved to the database, reducing our database calls to 1.

**Comment by lukemoorhous** [comment]
We'll want to look into this one as a team, review design options, then implement them as fast as we can before Milestone 2.

**Comment by lukemoorhous** [comment]
Implemented with #30
