### ISSUE TITLE
Investigate Github project management

### ISSUE THREAD

**Issue by lukemoorhous** [chandlerbrtek/receiptscanner#2]
Let's investigate and compare GitHub's project management tools with Trello.

**Comment by lukemoorhous** [comment]
Github allows for issues to be assigned to projects, individuals, and milestones. It also integrates directly with our git repository. Trello, however, provides a more intuitive interface.

Github Pros:
Integrates directly with git.

Github Cons:
Somewhat confusing setup and interface.

Trello Pros:
Simple interface and setup.

Trello Cons: Doesn't directly integrate with git. Integration may be possible, however.

**Comment by lukemoorhous** [comment]
Regardless of our choice, we will need to specify a set of procedures for specifying who's assigned what, what the priorities are, what needs to be done, what needs to be discussed, etc.

**Comment by chandlerbrtek** [comment]
I feel like Trello has its uses but I think GitHub is probably most useful. Not sure if it makes any sense to use both

**Comment by lukemoorhous** [comment]
Closing since we'll be using GitHub for commit tracking.
