### ISSUE TITLE
Pick a development environment: Android Studio vs Flutter

### ISSUE THREAD

**Issue by chandlerbrtek** [chandlerbrtek/receiptscanner#3]
Something we should probably decide at our next Sunday meeting. I've done a bit of looking into Flutter and it's difficult to tell if it would really be harder or easier to learn its respective language, Dart, over Kotlin for Android Studio. I think we will learn a lot either way, and perhaps not having the app on iOS isn't a big deal. I will do some more digging on the Flutter side before Sunday!

**Comment by svnphlps** [comment]
Flutter 10/10
